import {useEffect,useMemo,useState,type FormEvent} from "react";
import {ChevronLeft,ChevronRight,PiggyBank,Plus,Trash2} from "lucide-react";
import {financeRepository as repository} from "./repository";
import {formatMoney,parseMoney,type Account,type BudgetMonth,type Transaction} from "./domain";
import {SavingsGoals} from "./SavingsGoals";
import "./budget.css";

export function BudgetPage({transactions,accounts=[]}:{transactions:Transaction[];accounts?:Account[]}){
  const [month,setMonth]=useState(currentMonth()),[budget,setBudget]=useState<BudgetMonth>(),[drafts,setDrafts]=useState<Map<string,string>>(new Map());
  const [adding,setAdding]=useState(false),[pendingDelete,setPendingDelete]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const suggestions=useMemo(()=>[...new Set(transactions.flatMap(item=>item.splits?.length?item.splits.map(split=>split.category):[item.category]).filter(category=>category!=="Split transaction"&&!category.startsWith("Transfer:")))].sort(),[transactions]);
  useEffect(()=>{void load();},[month]);
  async function load(){try{const next=await repository.getBudgetMonth(month);setBudget(next);setDrafts(new Map(next.lines.map(item=>[item.id,(item.plannedMinor/100).toFixed(2)])));setError("");}catch(reason){show(reason);}}
  function show(reason:unknown){setError(reason instanceof Error?reason.message:String(reason));}
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);try{const plannedMinor=parseMoney(String(data.get("planned")));if(plannedMinor<0)throw new Error("Planned amount cannot be negative");const category=await repository.createBudgetCategory({category:String(data.get("category")||"").trim(),rolloverEnabled:data.get("rollover")==="on"});await repository.setBudgetAllocation({budgetCategoryId:category.id,month,plannedMinor});setAdding(false);await load();}catch(reason){show(reason);}finally{setBusy(false);}}
  async function save(id:string){setBusy(true);setError("");try{const plannedMinor=parseMoney(drafts.get(id)??"0");if(plannedMinor<0)throw new Error("Planned amount cannot be negative");await repository.setBudgetAllocation({budgetCategoryId:id,month,plannedMinor});await load();}catch(reason){show(reason);}finally{setBusy(false);}}
  async function rollover(id:string,category:string,rolloverEnabled:boolean){setBusy(true);try{await repository.updateBudgetCategory(id,{category,rolloverEnabled});await load();}catch(reason){show(reason);}finally{setBusy(false);}}
  async function remove(id:string){setBusy(true);try{await repository.deleteBudgetCategory(id);setPendingDelete("");await load();}catch(reason){show(reason);}finally{setBusy(false);}}
  const capacity=(budget?.plannedMinor??0)+(budget?.carryInMinor??0);
  return <div className="budget-page">
    <section className="panel budget-header"><div><h2>Monthly budget</h2><p>Plan spending by category. Rollover categories accumulate like sinking funds.</p></div><div className="month-switcher"><button aria-label="Previous month" onClick={()=>setMonth(shiftMonth(month,-1))}><ChevronLeft size={16}/></button><strong>{monthLabel(month)}</strong><button aria-label="Next month" onClick={()=>setMonth(shiftMonth(month,1))}><ChevronRight size={16}/></button></div></section>
    {error&&<div className="error-banner" role="alert">{error}</div>}
    <div className="summary-grid budget-summary"><Summary label="Planned" value={formatMoney(budget?.plannedMinor??0)}/><Summary label="Spent" value={formatMoney(budget?.spentMinor??0)} tone="negative"/><Summary label="Carried in" value={formatMoney(budget?.carryInMinor??0)} tone="positive"/><Summary label="Available" value={formatMoney(budget?.availableMinor??0)} tone={(budget?.availableMinor??0)<0?"negative":"positive"}/></div>
    <section className="panel budget-ledger"><div className="panel-heading"><div><h2>Categories</h2><p>{capacity?`${Math.round(((budget?.spentMinor??0)/capacity)*100)}% of available funds used`:"Add a category to begin planning"}</p></div><button onClick={()=>setAdding(true)}><Plus size={14}/> Add category</button></div>
      {!budget?.lines.length?<div className="empty-state"><PiggyBank size={24}/><span>No budget categories yet.</span></div>:<div className="budget-lines">{budget.lines.map(line=>{const total=line.plannedMinor+line.carryInMinor,percent=total>0?Math.min(100,Math.round(line.spentMinor/total*100)):0;return <article className="budget-line" key={line.id}><div className="budget-category"><strong>{line.category}</strong><label><input type="checkbox" checked={line.rolloverEnabled} disabled={busy} onChange={event=>void rollover(line.id,line.category,event.target.checked)}/> Rollover / sinking fund</label></div><div className="budget-progress"><div><span style={{width:`${percent}%`}}/></div><small>{formatMoney(line.spentMinor)} spent{line.carryInMinor?` · ${formatMoney(line.carryInMinor)} carried in`:""}</small></div><label className="budget-amount">Planned<input aria-label={`Planned amount for ${line.category}`} inputMode="decimal" value={drafts.get(line.id)??"0.00"} onChange={event=>setDrafts(current=>new Map(current).set(line.id,event.target.value))}/></label><div className={`budget-available ${line.availableMinor<0?"negative":"positive"}`}><span>Available</span><strong>{formatMoney(line.availableMinor)}</strong></div><div className="budget-actions"><button disabled={busy} onClick={()=>void save(line.id)}>Save</button>{pendingDelete===line.id?<><button onClick={()=>setPendingDelete("")}>Cancel</button><button className="danger-action" disabled={busy} onClick={()=>void remove(line.id)}>Confirm</button></>:<button aria-label={`Delete ${line.category}`} onClick={()=>setPendingDelete(line.id)}><Trash2 size={13}/></button>}</div></article>;})}</div>}
    </section>
    <SavingsGoals accounts={accounts}/>
    {adding&&<div className="dialog-backdrop"><section className="dialog budget-dialog" role="dialog" aria-modal="true" aria-labelledby="budget-dialog-title"><div className="dialog-header"><h2 id="budget-dialog-title">Add budget category</h2><button onClick={()=>setAdding(false)} aria-label="Close">×</button></div><form className="entry-form" onSubmit={add}><label>Category<input name="category" list="budget-category-options" maxLength={120} required autoFocus/><datalist id="budget-category-options">{suggestions.map(item=><option key={item} value={item}/>)}</datalist></label><label>Planned for {monthLabel(month)}<input name="planned" inputMode="decimal" defaultValue="0.00" required/></label><label className="rollover-choice"><input name="rollover" type="checkbox"/><span><strong>Carry unused funds forward</strong><small>Use this for irregular expenses and sinking funds.</small></span></label><div className="form-actions"><button type="button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Add category"}</button></div></form></section></div>}
  </div>;
}

function Summary({label,value,tone=""}:{label:string;value:string;tone?:string}){return <article className={`summary ${tone}`}><span>{label}</span><strong>{value}</strong></article>;}
function currentMonth(){const now=new Date();return`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;}
function shiftMonth(month:string,offset:number){const [year,value]=month.split("-").map(Number),date=new Date(year,value-1+offset,1);return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`;}
function monthLabel(month:string){return new Intl.DateTimeFormat("en-US",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${month}-01T00:00:00Z`));}
