import {useEffect,useMemo,useState,type FormEvent} from "react";
import {CircleDollarSign,Save,ShieldAlert} from "lucide-react";
import {formatMoney,parseMoney,type Account,type DebtPlan,type DebtStrategy} from "./domain";
import {calculateDebtProjection,type DebtProjection} from "./debtMath";
import {financeRepository as repository} from "./repository";
import "./debt.css";

const strategies:DebtStrategy[]=["snowball","avalanche","custom"];
const strategyCopy:Record<DebtStrategy,{label:string;detail:string}>={snowball:{label:"Snowball",detail:"Smallest current balance first"},avalanche:{label:"Avalanche",detail:"Highest APR first"},custom:{label:"Custom",detail:"Your priority order"}};

export function DebtPage({accounts,startMonth=currentMonth()}:{accounts:Account[];startMonth?:string}){
  const debtAccounts=accounts.filter(item=>["credit","loan"].includes(item.type)&&item.balanceMinor<0),currencies=[...new Set(debtAccounts.map(item=>item.currency))].sort();
  const [currency,setCurrency]=useState(currencies[0]??"USD"),[plan,setPlan]=useState<DebtPlan>(),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const scoped=debtAccounts.filter(item=>item.currency===currency);
  useEffect(()=>{if(currencies.length&&!currencies.includes(currency))setCurrency(currencies[0]);},[currencies,currency]);
  useEffect(()=>{let current=true;setLoading(true);setError("");void repository.getDebtPlan(currency).then(value=>{if(current){setPlan(value);setLoading(false);}}).catch(reason=>{if(current){setError(message(reason));setLoading(false);}});return()=>{current=false;};},[currency]);
  const projections=useMemo(()=>plan?Object.fromEntries(strategies.map(strategy=>[strategy,calculateDebtProjection({strategy,extraPaymentMinor:plan.extraPaymentMinor,startMonth,debts:plan.terms.map(term=>({...term,balanceMinor:Math.abs(accounts.find(item=>item.id===term.accountId)?.balanceMinor??0)}))})])) as Record<DebtStrategy,DebtProjection>:undefined,[accounts,plan,startMonth]);
  const selected=plan&&projections?.[plan.strategy];
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const data=new FormData(event.currentTarget);try{const terms=scoped.filter(account=>data.get(`enabled-${account.id}`)==="on").map((account,index)=>{const apr=Number(data.get(`apr-${account.id}`));if(!Number.isFinite(apr)||apr<0||apr>1000)throw new Error(`APR for ${account.name} must be between 0% and 1,000%`);const minimum=parseMoney(String(data.get(`minimum-${account.id}`)||"0"));if(minimum<=0)throw new Error(`Minimum payment for ${account.name} must be greater than zero`);return{accountId:account.id,annualRateBps:Math.round(apr*100),minimumPaymentMinor:minimum,customPriority:Number(data.get(`priority-${account.id}`))||index+1,enabled:true};});const saved=await repository.saveDebtPlan({currency,strategy:String(data.get("strategy")) as DebtStrategy,extraPaymentMinor:parseMoney(String(data.get("extraPayment")||"0")),terms});setPlan(saved);}catch(reason){setError(message(reason));}finally{setSaving(false);}}
  if(!debtAccounts.length)return <section className="panel empty-state">Add a credit-card or loan account with a balance to build a debt payoff plan.</section>;
  return <div className="debt-page">
    <section className="panel debt-header"><div><h2>Debt payoff planner</h2><p>Compare snowball, avalanche, and your own payoff order using deterministic local calculations.</p></div><label>Currency<select value={currency} onChange={event=>setCurrency(event.target.value)}>{currencies.map(item=><option key={item}>{item}</option>)}</select></label></section>
    {error&&<div className="error-banner" role="alert">{error}</div>}
    {loading||!plan?<section className="panel empty-state">Loading debt plan…</section>:<>
      <form className="panel debt-setup" onSubmit={save}><div className="panel-heading"><div><h2>Plan settings</h2><p>Only checked accounts participate; minimums remain fixed for this projection.</p></div><button className="primary-action" disabled={saving}><Save size={14}/>{saving?"Saving…":"Save and recalculate"}</button></div><div className="debt-settings"><label>Strategy<select name="strategy" defaultValue={plan.strategy}>{strategies.map(item=><option key={item} value={item}>{strategyCopy[item].label}</option>)}</select></label><label>Extra monthly payment<input name="extraPayment" inputMode="decimal" defaultValue={(plan.extraPaymentMinor/100).toFixed(2)}/></label><label>First payment month<input name="startMonth" value={startMonth} readOnly/><small>Projection timing; no ledger entries are created.</small></label></div><div className="table-wrap"><table className="debt-input-table"><thead><tr><th>Include</th><th>Debt account</th><th>Current balance</th><th>APR</th><th>Monthly minimum</th><th>Custom order</th></tr></thead><tbody>{scoped.map((account,index)=>{const term=plan.terms.find(item=>item.accountId===account.id);return <tr key={`${account.id}-${plan.currency}-${plan.strategy}-${plan.extraPaymentMinor}`}><td><input aria-label={`Include ${account.name}`} name={`enabled-${account.id}`} type="checkbox" defaultChecked={term?.enabled}/></td><td><strong>{account.name}</strong><small>{account.type==="credit"?"Credit card":"Loan"}</small></td><td className="amount negative">{formatMoney(Math.abs(account.balanceMinor),currency)}</td><td><input aria-label={`APR for ${account.name}`} name={`apr-${account.id}`} inputMode="decimal" defaultValue={term?(term.annualRateBps/100).toFixed(2):""} placeholder="0.00"/></td><td><input aria-label={`Minimum payment for ${account.name}`} name={`minimum-${account.id}`} inputMode="decimal" defaultValue={term?(term.minimumPaymentMinor/100).toFixed(2):""} placeholder="0.00"/></td><td><input aria-label={`Priority for ${account.name}`} name={`priority-${account.id}`} type="number" min="1" max="1000" defaultValue={term?.customPriority??index+1}/></td></tr>;})}</tbody></table></div></form>
      {!plan.terms.length?<section className="panel empty-state">Choose at least one debt account and save the plan to see projections.</section>:<>
        <div className="strategy-grid">{strategies.map(strategy=><StrategyCard key={strategy} projection={projections![strategy]} selected={plan.strategy===strategy} currency={currency}/>)}</div>
        {selected&&!selected.complete&&<div className="debt-warning"><ShieldAlert size={18}/><div><strong>This plan does not pay off within 100 years.</strong><span>Increase minimum or extra payments, or correct the APR, before relying on the projection.</span></div></div>}
        {selected&&<section className="panel debt-results"><div className="panel-heading"><div><h2>{strategyCopy[plan.strategy].label} payoff schedule</h2><p>{strategyCopy[plan.strategy].detail} · {formatMoney(selected.monthlyPaymentMinor,currency)} planned each month</p></div><strong>{selected.complete?monthLabel(selected.debtFreeMonth!):"Beyond 100 years"}</strong></div><div className="table-wrap"><table><thead><tr><th>Payoff order</th><th>Account</th><th>Starting balance</th><th>APR</th><th>Projected payoff</th><th>Interest paid</th></tr></thead><tbody>{selected.payoffOrder.map((id,index)=>{const account=scoped.find(item=>item.id===id)!,term=plan.terms.find(item=>item.accountId===id)!,line=selected.debts.find(item=>item.accountId===id)!;return <tr key={id}><td>{index+1}</td><td><strong>{account.name}</strong></td><td>{formatMoney(Math.abs(account.balanceMinor),currency)}</td><td>{(term.annualRateBps/100).toFixed(2)}%</td><td>{line.payoffMonth?monthLabel(line.payoffMonth):"Not paid off"}</td><td>{formatMoney(line.interestMinor,currency)}</td></tr>;})}</tbody></table></div></section>}
        {selected&&<section className="panel debt-timeline"><div className="panel-heading"><div><h2>Balance checkpoints</h2><p>Beginning monthly, then annual checkpoints and the final projected month</p></div></div><div className="debt-checkpoints">{checkpoints(selected).map(item=><article key={item.month}><span>{monthLabel(item.month)}</span><strong>{formatMoney(item.balanceMinor,currency)}</strong><small>{formatMoney(item.interestMinor,currency)} interest · {formatMoney(item.paymentMinor,currency)} paid</small></article>)}</div></section>}
      </>}
      <p className="debt-note">Projections assume fixed APRs and fixed entered minimums, with interest rounded to the nearest cent monthly. Saving a plan never posts payments or changes account balances.</p>
    </>}
  </div>;
}

function StrategyCard({projection,selected,currency}:{projection:DebtProjection;selected:boolean;currency:string}){const copy=strategyCopy[projection.strategy];return <article className={`strategy-card ${selected?"active":""}`}><span>{copy.label}{selected&&<em>Selected</em>}</span><strong>{projection.complete?monthLabel(projection.debtFreeMonth!):"100+ years"}</strong><small>{copy.detail}</small><dl><div><dt>Interest</dt><dd>{formatMoney(projection.totalInterestMinor,currency)}</dd></div><div><dt>Months</dt><dd>{projection.complete?projection.months:"—"}</dd></div></dl></article>;}
function checkpoints(projection:DebtProjection){return projection.timeline.filter((_,index)=>index<3||(index+1)%12===0||index===projection.timeline.length-1).filter((item,index,rows)=>index===0||item.month!==rows[index-1].month);}
function currentMonth(){return new Date().toISOString().slice(0,7);}
function monthLabel(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}-01T00:00:00Z`));}
function message(reason:unknown){return reason instanceof Error?reason.message:String(reason);}
