import {describe,expect,it} from "vitest";import type {Account,PortfolioSnapshot} from "./domain";import {calculateHouseholdValuation,householdCurrencies} from "./householdValuation";
const a=(id:string,type:Account["type"],currency:string,balanceMinor:number,archived=false):Account=>({id,name:id,type,currency,balanceMinor,ownerLabel:"Household",archived});
describe("household valuation",()=>{
 it("keeps ordinary-only net worth correct and excludes archived accounts",()=>{const v=calculateHouseholdValuation([a("cash","checking","USD",10000),a("card","credit","USD",-2500),a("old","savings","USD",999999,true)],undefined,"USD");expect(v).toMatchObject({assetsKnownMinor:10000,liabilitiesMinor:-2500,netWorthKnownMinor:7500,incompleteInvestment:false});});
 it("uses Foundation investment cash and holdings, never Account.balanceMinor",()=>{const accounts=[a("checking","checking","USD",10000),a("inv","investment","USD",999999)];const snapshot:PortfolioSnapshot={asOfDate:"2026-09-22",accounts:[{accountId:"inv",cashMinor:2000,holdingsValueMinor:5000,totalValueMinor:7000,holdings:[{accountId:"inv",securityId:"sec",quantityE8:100000000,knownBasisMinor:4000,unknownBasisQuantityE8:0,priceE8:5000000000,marketValueMinor:5000,unrealizedGainMinor:1000,incompleteUnknownBasis:false,lots:[],realized:{knownBasisQuantityE8:0,knownDisposedBasisMinor:0,calculableProceedsMinor:0,calculableGainMinor:0,unknownBasisQuantityE8:0,unknownBasisProceedsMinor:0,incompleteUnknownBasis:false}}]}]};const v=calculateHouseholdValuation(accounts,snapshot,"USD");expect(v.investmentKnownMinor).toBe(7000);expect(v.assetsKnownMinor).toBe(17000);expect(v.netWorthKnownMinor).toBe(17000);});
 it("preserves known cash while marking an unpriced holding incomplete",()=>{const snapshot:PortfolioSnapshot={asOfDate:"2026-09-22",accounts:[{accountId:"inv",cashMinor:2500,holdings:[{accountId:"inv",securityId:"sec",quantityE8:100000000,knownBasisMinor:9000,unknownBasisQuantityE8:0,incompleteUnknownBasis:false,lots:[],realized:{knownBasisQuantityE8:0,knownDisposedBasisMinor:0,calculableProceedsMinor:0,calculableGainMinor:0,unknownBasisQuantityE8:0,unknownBasisProceedsMinor:0,incompleteUnknownBasis:false}}]}]};const v=calculateHouseholdValuation([a("inv","investment","USD",0)],snapshot,"USD");expect(v).toMatchObject({investmentKnownMinor:2500,netWorthKnownMinor:2500,incompleteInvestment:true,unvaluedHoldingCount:1});});
 it("never combines currencies",()=>{const accounts=[a("usd","checking","USD",10000),a("eur","checking","EUR",20000),a("inv","investment","EUR",0)];const snapshot:PortfolioSnapshot={asOfDate:"2026-09-22",accounts:[{accountId:"inv",cashMinor:3000,holdings:[],holdingsValueMinor:0,totalValueMinor:3000}]};expect(householdCurrencies(accounts)).toEqual(["EUR","USD"]);expect(calculateHouseholdValuation(accounts,snapshot,"USD").netWorthKnownMinor).toBe(10000);expect(calculateHouseholdValuation(accounts,snapshot,"EUR").netWorthKnownMinor).toBe(23000);});
 it("available cash remains liquid ordinary cash rather than portfolio value or other assets",()=>{const accounts=[a("checking","checking","USD",1000),a("house","asset","USD",50000),a("inv","investment","USD",0)];const snapshot:PortfolioSnapshot={asOfDate:"2026-09-22",accounts:[{accountId:"inv",cashMinor:500,holdings:[],holdingsValueMinor:0,totalValueMinor:500}]};expect(calculateHouseholdValuation(accounts,snapshot,"USD").availableCashMinor).toBe(1000);});
 it("ordinary↔investment cash transfer only moves value between accounts",()=>{
  const beforeAccounts=[a("checking","checking","USD",500000),a("inv","investment","USD",0)];
  const beforeSnapshot:PortfolioSnapshot={asOfDate:"2026-09-22",accounts:[{accountId:"inv",cashMinor:100000,holdings:[],holdingsValueMinor:0,totalValueMinor:100000}]};
  const before=calculateHouseholdValuation(beforeAccounts,beforeSnapshot,"USD");
  const afterAccounts=[a("checking","checking","USD",400000),a("inv","investment","USD",0)];
  const afterSnapshot:PortfolioSnapshot={asOfDate:"2026-09-22",accounts:[{accountId:"inv",cashMinor:200000,holdings:[],holdingsValueMinor:0,totalValueMinor:200000}]};
  const after=calculateHouseholdValuation(afterAccounts,afterSnapshot,"USD");
  expect(before.netWorthKnownMinor).toBe(600000);
  expect(after.netWorthKnownMinor).toBe(600000);
  expect(after.availableCashMinor).toBe(400000);
  expect(after.investmentKnownMinor).toBe(200000);
 });
});