import {useEffect,useMemo,useState} from "react";import {Download} from "lucide-react";import {formatMoney,type Account,type InvestmentEventRevision,type PortfolioSnapshot,type Security} from "./domain";import {investmentRepository,csvExportRepository} from "./repository";import {calculateInvestmentReport} from "./investmentReport";import {buildInvestmentReportCsv,exportFileName} from "./csvExport";import {formatDate,todayIso} from "./scheduledPresentation";

export function InvestmentReportPanel({accounts,today=todayIso()}:{accounts:Account[];today?:string}){
 const active=useMemo(()=>accounts.filter(a=>!a.archived&&a.type==="investment"),[accounts]),currencies=useMemo(()=>[...new Set(active.map(a=>a.currency))].sort(),[active]);
 const [currency,setCurrency]=useState(currencies[0]??"USD"),[accountId,setAccountId]=useState("all"),[asOfDate,setAsOfDate]=useState(today),[fromDate,setFromDate]=useState(today.slice(0,4)+"-01-01");
 const [snapshot,setSnapshot]=useState<PortfolioSnapshot>(),[securities,setSecurities]=useState<Security[]>([]),[events,setEvents]=useState<InvestmentEventRevision[]>([]),[error,setError]=useState(""),[exporting,setExporting]=useState(false),[notice,setNotice]=useState("");
 const available=active.filter(a=>a.currency===currency);useEffect(()=>{if(currencies.length&&!currencies.includes(currency))setCurrency(currencies[0]);},[currencies,currency]);useEffect(()=>{if(accountId!=="all"&&!available.some(a=>a.id===accountId))setAccountId("all");},[accountId,available]);
 useEffect(()=>{let cancelled=false;const selected=available.filter(a=>accountId==="all"||a.id===accountId),ids=selected.map(a=>a.id);if(!ids.length){setSnapshot({asOfDate,accounts:[]});setEvents([]);return;}Promise.all([investmentRepository.calculatePortfolioSnapshot(ids,asOfDate),investmentRepository.listSecurities(true),...ids.map(id=>investmentRepository.listInvestmentEvents(id,fromDate,asOfDate))]).then(([s,sec,...eventLists])=>{if(!cancelled){setSnapshot(s as PortfolioSnapshot);setSecurities(sec as Security[]);setEvents((eventLists as InvestmentEventRevision[][]).flat());setError("");}}).catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:String(reason));});return()=>{cancelled=true};},[accountId,asOfDate,fromDate,currency,available.map(a=>a.id).join("|")]);
 const report=useMemo(()=>snapshot?calculateInvestmentReport({snapshot,events,accounts,securities,currency}):undefined,[snapshot,events,accounts,securities,currency]);
 async function exportReport(){if(!report)return;setExporting(true);setNotice("");try{const saved=await csvExportRepository.saveCsv(buildInvestmentReportCsv(report),exportFileName("HomeLedger-investments",fromDate,asOfDate));if(saved)setNotice("Investment report CSV saved.");}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setExporting(false);}}
 return <div className="investment-report"><section className="panel reports-header"><div><h2>Investments</h2><p>Foundation-backed holdings, gain/loss and investment income. Buys and sales stay outside household income/spending.</p></div><div className="reports-controls"><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}>{currencies.length?currencies.map(c=><option key={c}>{c}</option>):<option>USD</option>}</select></label><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="all">All active {currency} investment accounts</option>{available.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Income from<input type="date" max={asOfDate} value={fromDate} onChange={e=>setFromDate(e.target.value)}/></label><label>As of<input type="date" value={asOfDate} onChange={e=>setAsOfDate(e.target.value)}/></label><button className="report-export" disabled={!report||exporting} onClick={()=>void exportReport()}><Download size={13}/>{exporting?"Preparing…":"Export CSV"}</button></div></section>
 {error&&<div className="error-banner" role="alert">{error}</div>}{notice&&<div className="success-banner" role="status">{notice}</div>}
 {!report?null:<><div className="summary-grid report-summary"><Summary label="Market value" value={formatMoney(report.marketValueKnownMinor,currency)} detail={report.unrealizedIncomplete?"Known subtotal · missing valuation remains Unknown":"Saved prices eligible as of selected date"}/><Summary label="Known basis" value={formatMoney(report.knownBasisMinor,currency)} detail={report.rows.some(r=>r.basisPartial)?"Partial — some basis is Unknown":"Foundation-known cost basis"}/><Summary label="Unrealized gain/loss" value={formatMoney(report.unrealizedGainKnownMinor,currency)} detail={report.unrealizedIncomplete?"Known subtotal only":"Known basis compared with eligible saved prices"}/><Summary label="Realized gain/loss" value={formatMoney(report.realizedGainMinor,currency)} detail={report.realizedIncomplete?"Known-basis subtotal · unknown-basis proceeds excluded":"Foundation realized results through as-of date"}/></div>
 <section className="panel"><div className="panel-heading"><div><h2>Holdings as of {formatDate(asOfDate)}</h2><p>Historical valuation never uses a saved price dated after the selected as-of date.</p></div></div>{report.rows.length===0?<div className="empty-state">No active investment holdings in this scope.</div>:<div className="table-wrap"><table><thead><tr><th>Security</th><th>Account</th><th>Quantity</th><th>Price / observation</th><th>Market value</th><th>Known basis</th><th>Unrealized</th><th>Realized</th></tr></thead><tbody>{report.rows.map(r=><tr key={r.accountId+":"+r.securityId}><td><strong>{r.symbol??r.securityName}</strong><small>{r.symbol?r.securityName:""}</small></td><td>{r.accountName}</td><td>{quantity(r.quantityE8)}</td><td>{r.priceE8===undefined?"Unknown":price(r.priceE8,currency)+" · "+formatDate(r.priceObservedAt??asOfDate)}</td><td>{r.marketValueMinor===undefined?"Unknown":formatMoney(r.marketValueMinor,currency)}</td><td>{formatMoney(r.knownBasisMinor,currency)}{r.basisPartial?<small>Partial</small>:null}</td><td>{r.unrealizedGainMinor===undefined?"Unknown":formatMoney(r.unrealizedGainMinor,currency)}</td><td>{formatMoney(r.realizedGainMinor,currency)}{r.realizedPartial?<small>Partial · unknown basis</small>:null}</td></tr>)}</tbody></table></div>}</section>
 <div className="reports-grid"><section className="panel"><div className="panel-heading"><div><h2>Investment income</h2><p>{formatDate(fromDate)} – {formatDate(asOfDate)}</p></div></div><Metric label="Dividends" value={report.income.dividendMinor} currency={currency} note={report.income.reinvestedDividendMinor?formatMoney(report.income.reinvestedDividendMinor,currency)+" reinvested":undefined}/><Metric label="Interest" value={report.income.interestMinor} currency={currency}/><Metric label="Return of capital" value={report.income.returnOfCapitalMinor} currency={currency} note="Shown separately; not labeled income"/><Metric label="Fees / commissions" value={report.income.feesMinor} currency={currency}/></section><section className="panel"><div className="panel-heading"><div><h2>Realized results</h2><p>Foundation-known dispositions through {formatDate(asOfDate)}; this is not tax-return reporting.</p></div></div><Metric label="Known disposed basis" value={report.realizedKnownBasisMinor} currency={currency}/><Metric label="Calculable proceeds" value={report.realizedProceedsMinor} currency={currency}/><Metric label="Calculable gain/loss" value={report.realizedGainMinor} currency={currency}/><Metric label="Unknown-basis proceeds" value={report.realizedUnknownBasisProceedsMinor} currency={currency} note={report.realizedIncomplete?"No gain fabricated for this amount":undefined}/></section></div>
 <p className="report-note">Archived investment accounts are excluded from this current investment workspace. Currencies are reported separately; HomeLedger performs no FX conversion.</p></>}
 </div>;
}
function Summary({label,value,detail}:{label:string;value:string;detail:string}){return <article className="summary"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}function Metric({label,value,currency,note}:{label:string;value:number;currency:string;note?:string}){return <div className="portfolio-cash-row"><span>{label}{note?<small>{note}</small>:null}</span><strong>{formatMoney(value,currency)}</strong></div>}function quantity(v:number){return (v/100000000).toLocaleString("en-US",{maximumFractionDigits:8})}function price(v:number,currency:string){return new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:8}).format(v/100000000)}
