export interface MarketSecurity{providerSecurityId:string;symbol:string;name:string;exchange?:string;currency:string;securityType?:string}
export interface MarketQuote{providerSecurityId:string;price:string;currency:string;observedAt:string;provider:string}
export interface MarketHistoricalPrice{observedAt:string;price:string;currency:string;provider:string}
export interface MarketDataProvider{readonly id:string;readonly name:string;searchSecurities(query:string):Promise<MarketSecurity[]>;getQuote(identifier:string):Promise<MarketQuote>;getHistoricalPrices(identifier:string,fromDate:string,toDate:string):Promise<MarketHistoricalPrice[]>}
type FetchLike=typeof fetch;
function field(v:unknown):string{return typeof v==="string"?v:""}
function apiError(data:any):never{throw new Error(field(data?.Note)||field(data?.Information)||field(data?.["Error Message"])||"Market-data provider returned an invalid response.")}
export class AlphaVantageProvider implements MarketDataProvider{
 readonly id="alpha_vantage";readonly name="Alpha Vantage";constructor(private apiKey:string,private request:FetchLike=fetch){}
 private async call(params:Record<string,string>):Promise<any>{const u=new URL("https://www.alphavantage.co/query");Object.entries({...params,apikey:this.apiKey}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await this.request(u);if(!r.ok)throw new Error(`Market-data request failed (HTTP ${r.status}).`);return r.json();}
 async searchSecurities(query:string):Promise<MarketSecurity[]>{const d=await this.call({function:"SYMBOL_SEARCH",keywords:query});if(!Array.isArray(d.bestMatches))apiError(d);return d.bestMatches.map((x:any)=>({providerSecurityId:field(x["1. symbol"]),symbol:field(x["1. symbol"]),name:field(x["2. name"]),exchange:field(x["4. region"])||undefined,currency:field(x["8. currency"]).toUpperCase(),securityType:field(x["3. type"])||undefined})).filter((x:MarketSecurity)=>x.providerSecurityId&&x.name&&/^[A-Z]{3}$/.test(x.currency));}
 async getQuote(identifier:string):Promise<MarketQuote>{const d=await this.call({function:"GLOBAL_QUOTE",symbol:identifier});const q=d["Global Quote"];if(!q||!field(q["05. price"]))apiError(d);const date=field(q["07. latest trading day"]);return{providerSecurityId:identifier,price:field(q["05. price"]),currency:"",observedAt:date,provider:this.id};}
 async getHistoricalPrices(identifier:string,fromDate:string,toDate:string):Promise<MarketHistoricalPrice[]>{const d=await this.call({function:"TIME_SERIES_DAILY",symbol:identifier,outputsize:"compact"});const series=d["Time Series (Daily)"];if(!series||typeof series!=="object")apiError(d);return Object.entries(series).filter(([date])=>date>=fromDate&&date<=toDate).map(([date,row]:any)=>({observedAt:date,price:field(row["4. close"]),currency:"",provider:this.id}));}
}
export function normalizeProviderPrice(value:string):number{if(!/^(\d+)(?:\.(\d{1,8}))?$/.test(value))throw new Error("Provider returned unsupported price precision.");const [whole,fraction=""]=value.split(".");const n=BigInt(whole)*100_000_000n+BigInt(fraction.padEnd(8,"0"));if(n<=0n||n>BigInt(Number.MAX_SAFE_INTEGER))throw new Error("Provider returned an invalid price.");return Number(n);}
