import { useState } from "react";import type { Security } from "./domain";import { investmentRepository } from "./repository";import { AlphaVantageProvider,normalizeProviderPrice,type MarketSecurity } from "./marketData";
const NS="MARKET:ALPHA_VANTAGE";
export function MarketRefreshPanel({securities,asOfDate,onSaved}:{securities:Security[];asOfDate:string;onSaved:()=>void}){
 const [key,setKey]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [mapping,setMapping]=useState<{security:Security;results:MarketSecurity[]}>();
 async function refresh(){if(!key.trim()){setMessage("Enter an Alpha Vantage API key for this refresh. The key is not saved.");return;}setBusy(true);setMessage("");const provider=new AlphaVantageProvider(key.trim());let saved=0,unmapped=0,failed=0;
  try{for(const security of securities){try{const ids=await investmentRepository.listSecurityIdentifiers(security.id);const mapped=ids.find(i=>i.namespace===NS);if(!mapped){unmapped++;continue;}const quote=await provider.getQuote(mapped.value);if(!quote.observedAt||quote.observedAt>asOfDate){failed++;continue;}await investmentRepository.addMarketProviderSecurityPrice({securityId:security.id,observedAt:quote.observedAt,priceE8:normalizeProviderPrice(quote.price),currency:security.currency,provenance:`${provider.name} · ${mapped.value}`});saved++;}catch{failed++;}}setMessage(`Saved ${saved} observation${saved===1?"":"s"}.${unmapped?` ${unmapped} securit${unmapped===1?"y is":"ies are"} not mapped.`:""}${failed?` ${failed} refresh${failed===1?"":"es"} failed; existing prices were kept.`:""}`);if(saved)onSaved();}finally{setBusy(false);}}
 async function mapSecurity(security:Security){if(!key.trim()){setMessage("Enter an Alpha Vantage API key before searching.");return;}setBusy(true);try{const results=await new AlphaVantageProvider(key.trim()).searchSecurities(security.symbol??security.name);setMapping({security,results});if(!results.length)setMessage("No provider matches found. The HomeLedger security remains usable offline.");}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function choose(result:MarketSecurity){if(!mapping)return;if(result.currency!==mapping.security.currency){setMessage(`Currency mismatch: HomeLedger uses ${mapping.security.currency}; provider result uses ${result.currency}.`);return;}try{await investmentRepository.addSecurityIdentifier(mapping.security.id,NS,result.providerSecurityId);setMessage(`Mapped ${mapping.security.symbol??mapping.security.name} to ${result.symbol}. Refresh prices when ready.`);setMapping(undefined);}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 return <section className="panel market-refresh"><div className="panel-heading"><div><h2>Update prices</h2><p>Optional Internet-backed observations. Nothing is requested until you choose Refresh prices or Search.</p></div></div><div className="market-refresh-controls"><label>Alpha Vantage API key <input aria-label="Market data API key" type="password" value={key} onChange={e=>setKey(e.target.value)} autoComplete="off"/></label><button className="primary" disabled={busy} onClick={refresh}>{busy?"Working…":"Refresh prices"}</button></div><p className="market-note">The API key is used for this session only and is not saved. Saved observations remain available offline.</p>{message&&<div className="notice" role="status">{message}</div>}<div className="market-mappings"><strong>Security mappings</strong>{securities.map(s=><div key={s.id}><span>{s.symbol??s.name}</span><button disabled={busy} onClick={()=>mapSecurity(s)}>Search / map</button></div>)}</div>{mapping&&<div className="market-results"><h3>Choose the provider security for {mapping.security.symbol??mapping.security.name}</h3>{mapping.results.map(r=><button key={r.providerSecurityId} onClick={()=>choose(r)}><strong>{r.symbol}</strong> {r.name}<small>{r.exchange??"Unknown market"} · {r.currency}</small></button>)}<button onClick={()=>setMapping(undefined)}>Cancel</button></div>}</section>;
}