// @vitest-environment jsdom
import {afterEach,expect,it,vi} from "vitest";import {cleanup,fireEvent,render,screen} from "@testing-library/react";
vi.mock("./repository",()=>({investmentRepository:{listSecurityIdentifiers:vi.fn(),addSecurityIdentifier:vi.fn(),addMarketProviderSecurityPrice:vi.fn()}}));
import {MarketRefreshPanel} from "./MarketRefreshPanel";import {investmentRepository} from "./repository";
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.clearAllMocks();});
const security={id:"sec",securityType:"stock" as const,name:"Example",symbol:"EXM",currency:"USD",archived:false};
it("explicit Refresh prices retrieves then persists a normalized provider observation",async()=>{vi.mocked(investmentRepository.listSecurityIdentifiers).mockResolvedValue([{securityId:"sec",namespace:"MARKET:ALPHA_VANTAGE",value:"EXM"}]);vi.mocked(investmentRepository.addMarketProviderSecurityPrice).mockResolvedValue({id:"p",securityId:"sec",observedAt:"2026-09-21",priceE8:125_000_000,currency:"USD",source:"market_provider"});const network=vi.spyOn(globalThis,"fetch").mockResolvedValue({ok:true,status:200,json:async()=>({"Global Quote":{"05. price":"1.25","07. latest trading day":"2026-09-21"}})} as Response);const saved=vi.fn();render(<MarketRefreshPanel securities={[security]} asOfDate="2026-09-21" onSaved={saved}/>);expect(network).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText("Market data API key"),{target:{value:"secret"}});fireEvent.click(screen.getByRole("button",{name:"Refresh prices"}));await vi.waitFor(()=>expect(investmentRepository.addMarketProviderSecurityPrice).toHaveBeenCalledWith({securityId:"sec",observedAt:"2026-09-21",priceE8:125_000_000,currency:"USD",provenance:"Alpha Vantage · EXM"}));expect(saved).toHaveBeenCalled();});
it("unmapped securities remain usable and are reported without guessing",async()=>{vi.mocked(investmentRepository.listSecurityIdentifiers).mockResolvedValue([]);const network=vi.spyOn(globalThis,"fetch");render(<MarketRefreshPanel securities={[security]} asOfDate="2026-09-21" onSaved={()=>{}}/>);fireEvent.change(screen.getByLabelText("Market data API key"),{target:{value:"secret"}});fireEvent.click(screen.getByRole("button",{name:"Refresh prices"}));expect(await screen.findByText(/1 security is not mapped/)).toBeTruthy();expect(network).not.toHaveBeenCalled();expect(investmentRepository.addMarketProviderSecurityPrice).not.toHaveBeenCalled();});
it("provider failure leaves saved prices untouched and reports failure",async()=>{vi.mocked(investmentRepository.listSecurityIdentifiers).mockResolvedValue([{securityId:"sec",namespace:"MARKET:ALPHA_VANTAGE",value:"EXM"}]);vi.spyOn(globalThis,"fetch").mockRejectedValue(new Error("offline"));render(<MarketRefreshPanel securities={[security]} asOfDate="2026-09-21" onSaved={()=>{}}/>);fireEvent.change(screen.getByLabelText("Market data API key"),{target:{value:"secret"}});fireEvent.click(screen.getByRole("button",{name:"Refresh prices"}));expect(await screen.findByText(/1 refresh failed; existing prices were kept/)).toBeTruthy();expect(investmentRepository.addMarketProviderSecurityPrice).not.toHaveBeenCalled();});
it("rejects a quote that explicitly supplies a mismatched currency",async()=>{vi.mocked(investmentRepository.listSecurityIdentifiers).mockResolvedValue([{securityId:"sec",namespace:"MARKET:ALPHA_VANTAGE",value:"EXM"}]);vi.spyOn(globalThis,"fetch").mockResolvedValue({ok:true,status:200,json:async()=>({"Global Quote":{"05. price":"1.25","07. latest trading day":"2026-09-21"}})} as Response);const market=await import("./marketData");const original=market.AlphaVantageProvider.prototype.getQuote;vi.spyOn(market.AlphaVantageProvider.prototype,"getQuote").mockResolvedValue({providerSecurityId:"EXM",price:"1.25",currency:"EUR",observedAt:"2026-09-21",provider:"alpha_vantage"});render(<MarketRefreshPanel securities={[security]} asOfDate="2026-09-21" onSaved={()=>{}}/>);fireEvent.change(screen.getByLabelText("Market data API key"),{target:{value:"secret"}});fireEvent.click(screen.getByRole("button",{name:"Refresh prices"}));expect(await screen.findByText(/1 refresh failed/)).toBeTruthy();expect(investmentRepository.addMarketProviderSecurityPrice).not.toHaveBeenCalled();market.AlphaVantageProvider.prototype.getQuote=original;});
it("rejects mapping a known provider currency that differs from HomeLedger",async()=>{vi.spyOn(globalThis,"fetch").mockResolvedValue({ok:true,status:200,json:async()=>({bestMatches:[{"1. symbol":"EXM","2. name":"Example","3. type":"Equity","4. region":"Europe","8. currency":"EUR"}]})} as Response);render(<MarketRefreshPanel securities={[security]} asOfDate="2026-09-21" onSaved={()=>{}}/>);fireEvent.change(screen.getByLabelText("Market data API key"),{target:{value:"secret"}});fireEvent.click(screen.getByRole("button",{name:"Search / map"}));const result=await screen.findByRole("button",{name:/EXM Example/});fireEvent.click(result);expect(await screen.findByText(/Currency mismatch/)).toBeTruthy();expect(investmentRepository.addSecurityIdentifier).not.toHaveBeenCalled();});
