import { useEffect, useState, type FormEvent } from "react";
import { ListFilter, Pencil, Plus, X } from "lucide-react";
import { type MerchantRule, type MerchantRuleDirection, type MerchantRuleInput, type MerchantRuleMatchType } from "./domain";
import { normalizeMerchant } from "./merchantRules";
import { financeRepository as repository } from "./repository";
import { SuggestionLists, useLedgerSuggestions } from "./useLedgerSuggestions";
import "./rules.css";

export function RulesPage(){
  const [rules,setRules]=useState<MerchantRule[]>([]),[editing,setEditing]=useState<MerchantRule|"new"|null>(null);
  const [error,setError]=useState("");
  async function load(){try{setRules(await repository.listMerchantRules());setError("");}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  useEffect(()=>{void load();},[]);
  return <div className="rules-page"><section className="panel rules-intro"><div className="panel-heading"><div><h2>Merchant and category rules</h2><p>Deterministic rules run locally during statement import.</p></div><button onClick={()=>setEditing("new")}><Plus size={14}/> New rule</button></div><div className="rules-explainer"><ListFilter size={20}/><div><strong>Highest priority wins</strong><span>HomeLedger normalizes capitalization and punctuation before matching. Rules affect future imports only, and every match is shown during pre-import review.</span></div></div></section>{error&&<div className="error-banner" role="alert">{error}</div>}<section className="panel"><div className="panel-heading"><div><h2>Saved rules</h2><p>{rules.length} rule{rules.length===1?"":"s"}</p></div></div>{rules.length===0?<div className="empty-state">No rules yet. Add one for a merchant you see repeatedly.</div>:<div className="table-wrap"><table><thead><tr><th>Priority</th><th>Name</th><th>Match</th><th>Action</th><th>Scope</th><th>Status</th><th></th></tr></thead><tbody>{rules.map(rule=><tr key={rule.id}><td>{rule.priority}</td><td><strong>{rule.name}</strong></td><td><code>{matchLabel(rule.matchType)} “{rule.pattern}”</code></td><td>{[rule.renameTo&&`Rename to ${rule.renameTo}`,rule.category&&`Category: ${rule.category}`].filter(Boolean).join(" · ")}</td><td>{rule.direction}</td><td><span className={`rule-state ${rule.enabled?"enabled":"disabled"}`}>{rule.enabled?"Enabled":"Disabled"}</span></td><td><button className="edit-transaction" onClick={()=>setEditing(rule)}><Pencil size={12}/> Edit</button></td></tr>)}</tbody></table></div>}</section>{editing&&<RuleDialog rule={editing==="new"?undefined:editing} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load();}}/>}</div>;
}

export function RuleDialog({rule,draft,onClose,onSaved}:{rule?:MerchantRule;draft?:MerchantRuleInput;onClose:()=>void;onSaved:()=>Promise<void>}){
  const suggestions=useLedgerSuggestions();
  const seed=rule??draft;
  const [saving,setSaving]=useState(false),[error,setError]=useState(""),[confirmDelete,setConfirmDelete]=useState(false),[pattern,setPattern]=useState(seed?.pattern??"");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const data=new FormData(event.currentTarget);try{const input:MerchantRuleInput={name:String(data.get("name")||"").trim(),pattern:String(data.get("pattern")||"").trim(),matchType:String(data.get("matchType")) as MerchantRuleMatchType,direction:String(data.get("direction")) as MerchantRuleDirection,renameTo:String(data.get("renameTo")||"").trim()||undefined,category:String(data.get("category")||"").trim()||undefined,priority:Number(data.get("priority")),enabled:data.get("enabled")==="on"};if(rule)await repository.updateMerchantRule(rule.id,input);else await repository.createMerchantRule(input);await onSaved();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setSaving(false);}}
  async function remove(){if(!rule)return;if(!confirmDelete){setConfirmDelete(true);return;}setSaving(true);setError("");try{await repository.deleteMerchantRule(rule.id);await onSaved();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setSaving(false);setConfirmDelete(false);}}
  return <div className="dialog-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)onClose();}}><section className="dialog rule-dialog" role="dialog" aria-modal="true" aria-labelledby="rule-title"><div className="dialog-header"><h2 id="rule-title">{rule?"Edit merchant rule":draft?"Create merchant rule":"New merchant rule"}</h2><button onClick={onClose} aria-label="Close"><X size={18}/></button></div><form className="entry-form" onSubmit={submit}><label>Rule name<input name="name" defaultValue={seed?.name} required maxLength={80} autoFocus placeholder="Neighborhood Market groceries"/></label><div className="rule-match-grid"><label>Match type<select name="matchType" defaultValue={seed?.matchType??"contains"}><option value="contains">Contains</option><option value="starts_with">Starts with</option><option value="exact">Exact normalized text</option></select></label><label>Bank description contains<input name="pattern" value={pattern} onChange={event=>setPattern(event.target.value)} required maxLength={120} placeholder="NEIGHBORHOOD MARKET"/></label></div><p className="normalized-example">Normalized match: <code>{normalizeMerchant(pattern)||"—"}</code></p><div className="form-row"><label>Apply to<select name="direction" defaultValue={seed?.direction??"any"}><option value="any">Income and expenses</option><option value="expense">Expenses only</option><option value="income">Income only</option></select></label><label>Priority<input name="priority" type="number" min="-10000" max="10000" step="1" defaultValue={seed?.priority??100} required/></label></div><div className="form-row"><label>Rename merchant to<input name="renameTo" list={suggestions.payeeListId} defaultValue={seed?.renameTo} maxLength={160} placeholder="Neighborhood Market"/></label><label>Assign category<input name="category" list={suggestions.categoryListId} defaultValue={seed?.category} maxLength={120} placeholder="Food: Groceries"/></label></div><label className="enabled-check"><input name="enabled" type="checkbox" defaultChecked={seed?.enabled??true}/><span>Rule enabled</span></label><p className="mapping-help">Provide a renamed merchant, a category, or both. A category already supplied by QIF and all split categories remain unchanged.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="transaction-actions">{rule?<button type="button" className={confirmDelete?"danger-action":"delete-link"} disabled={saving} onClick={remove}>{confirmDelete?"Confirm rule deletion":"Delete rule"}</button>:<span/>}<div className="form-actions"><button type="button" onClick={onClose} disabled={saving}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving…":"Save rule"}</button></div></div><SuggestionLists {...suggestions}/></form></section></div>;
}

function matchLabel(value:MerchantRuleMatchType){return value==="starts_with"?"Starts with":value==="exact"?"Equals":"Contains";}
