import {useEffect,useState,type FormEvent} from "react";
import {Flag,Plus,Trash2} from "lucide-react";
import {formatMoney,parseMoney,type Account,type SavingsGoal,type SavingsGoalInput} from "./domain";
import {financeRepository as repository} from "./repository";
import {calculateSavingsGoal,type SavingsGoalStatus} from "./savingsGoalMath";

export function SavingsGoals({accounts,asOfDate=todayIso()}:{accounts:Account[];asOfDate?:string}){
  const [goals,setGoals]=useState<SavingsGoal[]>([]),[editing,setEditing]=useState<SavingsGoal|"new"|null>(null),[pendingDelete,setPendingDelete]=useState(""),[busy,setBusy]=useState(false);
  const [message,setMessage]=useState("");
  const savings=accounts.filter(item=>item.type==="savings"),available=savings.filter(account=>!goals.some(goal=>goal.accountId===account.id));
  useEffect(()=>{void load();},[]);
  async function load(){try{setGoals(await repository.listSavingsGoals());setMessage("");}catch(reason){setMessage(errorMessage(reason));}}
  async function save(input:SavingsGoalInput){setBusy(true);setMessage("");try{if(editing&&editing!=="new")await repository.updateSavingsGoal(editing.id,input);else await repository.createSavingsGoal(input);setEditing(null);await load();}catch(reason){setMessage(errorMessage(reason));setBusy(false);throw reason;}finally{setBusy(false);}}
  async function remove(id:string){if(pendingDelete!==id){setPendingDelete(id);return;}setBusy(true);setMessage("");try{await repository.deleteSavingsGoal(id);setPendingDelete("");await load();}catch(reason){setMessage(errorMessage(reason));}finally{setBusy(false);}}
  return <section className="panel savings-goals"><div className="panel-heading"><div><h2>Savings goals</h2><p>Progress uses the current balance of one dedicated savings account; goal planning never moves money.</p></div><button disabled={!available.length||busy} onClick={()=>setEditing("new")}><Plus size={14}/> Add goal</button></div>
    {message&&<div className="goal-error" role="alert">{message}</div>}
    {!savings.length?<div className="empty-state"><Flag size={22}/><span>Add a savings account before creating a goal.</span></div>:!goals.length?<div className="empty-state"><Flag size={22}/><span>No savings goals yet.</span></div>:<div className="goal-grid">{goals.map(goal=>{const account=accounts.find(item=>item.id===goal.accountId),projection=calculateSavingsGoal(goal,account?.balanceMinor??0,asOfDate);return <article className="goal-card" key={goal.id}><div className="goal-title"><div><strong>{goal.name}</strong><small>{account?.name??"Missing savings account"} · target {dateLabel(goal.targetDate)}</small></div><span className={`goal-status ${projection.status}`}>{statusLabel(projection.status)}</span></div><div className="goal-progress"><div><span style={{width:`${projection.progressPercent}%`}}/></div><small>{projection.progressPercent}% funded</small></div><div className="goal-numbers"><div><span>Saved</span><strong>{formatMoney(projection.currentMinor,account?.currency)}</strong></div><div><span>Remaining</span><strong>{formatMoney(projection.remainingMinor,account?.currency)}</strong></div><div><span>Required monthly</span><strong>{formatMoney(projection.requiredMonthlyMinor,account?.currency)}</strong></div><div><span>Planned monthly</span><strong>{formatMoney(goal.plannedMonthlyMinor,account?.currency)}</strong></div></div><p>{goal.plannedMonthlyMinor&&projection.projectedMonth?`At the planned rate: ${monthLabel(projection.projectedMonth)}.`:"Enter a monthly contribution to estimate completion."}</p><div className="goal-actions"><button disabled={busy} onClick={()=>setEditing(goal)}>Edit</button>{pendingDelete===goal.id?<><button onClick={()=>setPendingDelete("")}>Cancel</button><button className="danger-action" disabled={busy} onClick={()=>void remove(goal.id)}>Confirm delete</button></>:<button aria-label={`Delete ${goal.name}`} disabled={busy} onClick={()=>void remove(goal.id)}><Trash2 size={13}/></button>}</div></article>;})}</div>}
    {editing&&<GoalDialog goal={editing==="new"?undefined:editing} accounts={editing==="new"?available:savings.filter(account=>account.id===editing.accountId||available.some(item=>item.id===account.id))} asOfDate={asOfDate} busy={busy} onClose={()=>setEditing(null)} onSave={save}/>}
  </section>;
}

function GoalDialog({goal,accounts,asOfDate,busy,onClose,onSave}:{goal?:SavingsGoal;accounts:Account[];asOfDate:string;busy:boolean;onClose:()=>void;onSave:(input:SavingsGoalInput)=>Promise<void>}){
  const [error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=new FormData(event.currentTarget);try{const targetMinor=parseMoney(String(data.get("target"))),plannedMonthlyMinor=parseMoney(String(data.get("plannedMonthly"))),targetDate=String(data.get("targetDate"));if(targetMinor<=0)throw new Error("Savings target must be greater than zero");if(plannedMonthlyMinor<0)throw new Error("Planned monthly savings cannot be negative");if(!goal&&targetDate<=asOfDate)throw new Error("New savings goals need a future target date");await onSave({name:String(data.get("name")||"").trim(),accountId:String(data.get("accountId")),targetMinor,targetDate,plannedMonthlyMinor});}catch(reason){setError(errorMessage(reason));}}
  return <div className="dialog-backdrop"><section className="dialog goal-dialog" role="dialog" aria-modal="true" aria-labelledby="goal-dialog-title"><div className="dialog-header"><h2 id="goal-dialog-title">{goal?"Edit savings goal":"New savings goal"}</h2><button onClick={onClose} disabled={busy} aria-label="Close">×</button></div><form className="entry-form" onSubmit={submit}><label>Goal name<input name="name" defaultValue={goal?.name} required maxLength={120} autoFocus/></label><label>Savings account<select name="accountId" defaultValue={goal?.accountId??accounts[0]?.id} required>{accounts.map(account=><option key={account.id} value={account.id}>{account.name} · {formatMoney(account.balanceMinor,account.currency)}</option>)}</select><small>The full current balance counts toward this goal.</small></label><div className="form-row"><label>Target amount<input name="target" inputMode="decimal" defaultValue={goal?(goal.targetMinor/100).toFixed(2):""} required/></label><label>Target date<input name="targetDate" type="date" defaultValue={goal?.targetDate} required/></label></div><label>Planned monthly contribution<input name="plannedMonthly" inputMode="decimal" defaultValue={goal?(goal.plannedMonthlyMinor/100).toFixed(2):"0.00"} required/><small>This is a plan only; HomeLedger does not transfer funds.</small></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save goal"}</button></div></form></section></div>;
}

function statusLabel(status:SavingsGoalStatus){return status==="on-track"?"On track":status==="at-risk"?"At risk":status[0].toUpperCase()+status.slice(1);}
function todayIso(){return new Date().toISOString().slice(0,10);}
function dateLabel(value:string){return new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));}
function monthLabel(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}-01T00:00:00Z`));}
function errorMessage(reason:unknown){return reason instanceof Error?reason.message:String(reason);}
